repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
  - repo: local
    hooks:
      - id: cpitd-clone-detection
        name: cpitd (clone detection)
        entry: cpitd cpitd/ --ignore "tests/fixtures/*" --suppress "*@protocol_impl*"
        language: system
        pass_filenames: false
        always_run: true
